# Generated by Django 4.1.13 on 2025-07-27 10:41

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattachment',
            name='handle',
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\shind\\OneDrive\\Desktop\\desktop things\\django learning\\e-commerce\\micro-ecommerce\\local-cdn\\protected'), upload_to=products.models.handle_product_attachment_upload),
        ),
    ]
