# Generated by Django 4.1.13 on 2025-07-30 20:15

import cfehome.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cfehome.storage.B2Storage(), upload_to='products/'),
        ),
    ]
